### ISSUE TITLE
Unit tests and code coverage

### ISSUE THREAD

**Issue by andriisoldatenko** [elbuo8/sendgrid-django#36]
I would like to propose to start writing tests, add code coverage and small testing on different python versions to avoid issues.

# TODO:
- [x] Create first test
- [x] Integrate with travis
- [x] Setup tox
- [x] Add something like https://codecov.io/.

elbuo8/sendgrid-django#46

**Comment by andriisoldatenko** [comment]
@elbuo8 Can you please assist me to integrate with travis?

**Comment by elbuo8** [comment]
For sure. I'm still in holidays. Monday sounds good?

**Comment by andriisoldatenko** [comment]
Yes sure :)

**Comment by elbuo8** [comment]
@andriisoldatenko enabled TravisCI for this repo. Seems like you have the config file ready. I understand that if you make a new push to the branch it should pick it up.

**Comment by andriisoldatenko** [comment]
@elbuo8 works! Can you please also add https://codecov.io/.
Thanks in advance.

**Comment by elbuo8** [comment]
@andriisoldatenko https://github.com/codecov/example-python/blob/master/.travis.yml#L14

I've enabled the repo already.

**Comment by andriisoldatenko** [comment]
@elbuo8 works great! Thanks
